# Generated by Django 3.2 on 2024-01-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('detenido ', 'Detenido'), ('finalizado', 'Finalizado')], default='activo', max_length=20),
        ),
    ]
