# Generated by Django 3.2 on 2024-01-27 06:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyecto', '0002_alter_proyecto_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='usuarios_con_permisos',
            field=models.ManyToManyField(blank=True, related_name='proyectos_con_permisos', to=settings.AUTH_USER_MODEL),
        ),
    ]
