# Generated by Django 3.2 on 2024-02-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0003_proyecto_usuarios_con_permisos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Detenido ', 'Detenido'), ('Finalizado', 'Finalizado')], default='Activo', max_length=20),
        ),
    ]
