# Generated by Django 3.2 on 2024-02-02 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarea', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarea',
            old_name='asignado_a',
            new_name='usuario_asignado',
        ),
    ]
