# Generated by Django 3.2 on 2024-02-09 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentario', '0002_alter_comentario_tarea'),
        ('tarea', '0002_rename_asignado_a_tarea_usuario_asignado'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='comentarios',
            field=models.ManyToManyField(related_name='tarea_comentarios', to='comentario.Comentario'),
        ),
    ]
